# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "uas" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/01fd5fe3-4d40-4745-aa97-d770fb733965";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/01fd5fe3-4d40-4745-aa97-d770fb733965";
      fsType = "btrfs";
      options = [ "noatime" "subvol=@swap" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/01fd5fe3-4d40-4745-aa97-d770fb733965";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/01fd5fe3-4d40-4745-aa97-d770fb733965";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/01fd5fe3-4d40-4745-aa97-d770fb733965";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2270-0B1F";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # --- 启用交换空间 ---
  swapDevices = [{
    device = "/swap/swapfile";
    # 大小可以设置为当前机器内存的 1.5 或是 2.0 倍 (单位: MiB)
    size = 24 * 1024;
  }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
